import { describe, it, expect, vi } from 'vitest';
import * as uuid from 'uuid';

import { generatePairingCode } from './socket-state.js';

vi.mock('uuid', () => ({
    v7: vi.fn(),
}));

describe('generateClientId', () => {
    it('should return a UUID generated by uuid.v7', () => {
        const mockUuid = '123e4567-e89b-12d3-a456-426614174000';
        (uuid.v7 as ReturnType<typeof vi.fn>).mockReturnValue(mockUuid);

        const clientId = generatePairingCode();

        expect(uuid.v7).toHaveBeenCalled();
        expect(clientId).toBe(mockUuid);
    });
});
